<a href="https://colab.research.google.com/github/challabala/AI-ML/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy (Numerical Python) is a powerful Python library used for numerical and scientific computing.
It provides an efficient multi-dimensional array object called ndarray, along with tools for:

*  Mathematical operations

*  Statistical functions

*  Linear algebra

*  Random number generation

*  Broadcasting

**Key Idea** :
NumPy replaces slow Python lists with fast and memory-efficient arrays, enabling high-performance computations.



*   Features of NumPy
*   Fast numerical computations
*   Support for multi-dimensional arrays
*   Vectorized operations
*   Large library of mathematical functions



**Speed Comparision**

In [ ]:
# Python List
import time

l = list(range(1_000_000))

start = time.time()
l2 = [x * 2 for x in l]
print("List time:", time.time() - start)


List time: 0.09938335418701172


In [ ]:
# Numpy Arrays
import numpy as np

a = np.arange(1_000_000)

start = time.time()
a2 = a * 2
print("Array time:", time.time() - start)


Array time: 0.0028047561645507812


**Applications of NumPy**


1.   Data Science
2.   Machine Learning
3.   Scientific Computing
4.   Visualization
5.   Engineering Domains



In [ ]:
import numpy as np
print(np.__version__) # np → alias used everywhere (industry standard)


2.0.2


In [ ]:
import numpy as np
import sys

l = [1, 2, 3, 4]
a = np.array([1, 2, 3, 4])

print("List size:", sys.getsizeof(l))
print("Array size:", a.nbytes)


List size: 88
Array size: 32


**Chapter** - **1**

**Understanding ndarray**

ndarray (N-Dimensional Array) is the core data structure of NumPy.
It represents a homogeneous (same-type) multi-dimensional array used for:

In [ ]:
print(np.array([1,2,3,4]))
print(np.array([[1,2],[3,4]]))

[1 2 3 4]
[[1 2]
 [3 4]]


In [ ]:
print(np.zeros((2,3)))
print(np.ones((3,3)))
print(np.arange(1, 10, 2))
print(np.linspace(0, 1, 5))
print(np.random.randint(1, 100, 5))


[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[1 3 5 7 9]
[0.   0.25 0.5  0.75 1.  ]
[75 35 91 80 29]


In [ ]:
arr = np.array([10,20,30,40])
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)
print(arr.nbytes)

int64
1
(4,)
4
8
32


In [ ]:
import numpy as np

a = np.array([[10, 20, 30],
              [40, 50, 60]])

print("Array:\n", a)
print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)
print("itemsize:", a.itemsize)
print("nbytes:", a.nbytes)


Array:
 [[10 20 30]
 [40 50 60]]
ndim: 2
shape: (2, 3)
size: 6
dtype: int64
itemsize: 8
nbytes: 48


**Chapter - 2**

**Array Creation Functions**

In [ ]:
# From the list
# np.array(list)
li = [1,2,3,4,5,6,7,8]
print(np.array(l))

[1 2 3 4]


In [ ]:
# from the tuple
# np.array((tuple))
arr = np.array((1, 2, 3, 4))
print(arr)


[1 2 3 4]


In [ ]:
# NumPy Built-in Array
# 1 np.array()
np.array([1, 2, 3])
np.array([[1, 2], [3, 4]])


array([[1, 2],
       [3, 4]])

In [ ]:
# 2 np.arange()
# np.arange(start, stop, step)
print(np.arange(1, 100, 3))

[ 1  4  7 10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70
 73 76 79 82 85 88 91 94 97]


In [ ]:
# 3 np.linspace()
# np.linspace(start, end, number_of_values)
print(np.linspace(0, 1, 5))
print(np.linspace(0, 100, 10))


[0.   0.25 0.5  0.75 1.  ]
[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [ ]:
# np.zeros()
# np.zeros(shape)
print(np.zeros((2, 3)))
print(np.ones((3, 3)))

# np.empty() ----- Creates an uninitialized array (contains random garbage values).
print(np.empty((2, 3)))

# np.full((3, 3), 7)
# Creates an array filled with a given constant.
print(np.full((3, 3), 100))

# np.eye()
# Creates a 2D identity-like matrix with ones on the diagonal.
print(np.eye(3))

# np.identity()
# Creates a square identity matrix (similar to eye).
print(np.identity(3))

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[100 100 100]
 [100 100 100]
 [100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Array Creation Using NumPy Random Module

NumPy provides powerful random generation functions for ML, AI, and simulation tasks.

In [ ]:
# np.random.rand()
# Generates random floats in the range [0,1).
print(np.random.rand(2, 3))

# np.random.randn()
# Generates random values from a standard normal distribution (mean=0, std=1).
print(np.random.randn(2, 3))

# np.random.randint()
# Generates random integers within a specified range.
print(np.random.randint(1, 100, 5))

# np.random.random()
# Generates random floats in the range [0,1) (similar to rand()).
print(np.random.random((2, 3)))


[[0.04090405 0.76151525 0.73462219]
 [0.49383452 0.75126848 0.72010221]]
[[-0.98461158  0.49806584  0.00461063]
 [-3.16651521 -1.34702618 -1.06777091]]
[51 86 47 45 47]
[[0.67448009 0.38598765 0.72503404]
 [0.03634393 0.27415181 0.69120467]]


**Chapter - 3**
**Indexing & Slicing**

In [ ]:
import numpy as np
# Indexing : arr[index]
# Indexing works the same as Python lists.

arr = np.array([10, 20, 30, 40, 50])
print(arr[0])     # First element
print(arr[-1])    # Last element


10
50


In [ ]:
# Slicing
# Slicing extracts a portion of an array.

# Syntax
# arr[start : end : step]

print(arr[1:4])      # elements from index 1 to 3
print(arr[:3])       # first 3 elements
print(arr[::2])      # step slicing

[20 30 40]
[10 20 30]
[10 30 50]
